name: CD - Deploy to EC2

on:
  workflow_run:
    workflows: ["CI - Docker Build & Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
            docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/myapp:latest
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp \
              -p 8080:8080 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e DB_URL="${{ secrets.DB_URL }}" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              ghcr.io/${{ secrets.GHCR_USERNAME }}/myapp:latest
            echo "⏳ Waiting for app to start..."
            sleep 20
            echo "🔍 Checking health..."
            if ! curl -f http://localhost:8080/actuator/health; then
              echo "❌ Health check failed! Printing container logs..."
              docker logs myapp
              exit 1
            fi